# Generated by Django 5.0.3 on 2024-03-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0006_delete_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=255)),
                ('books_name', models.CharField(max_length=255)),
                ('name_of_author', models.CharField(max_length=255)),
                ('dept_name', models.CharField(max_length=100)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
    ]
