# Generated by Django 5.0.3 on 2024-03-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0008_rename_books_name_student_purchase_book_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=255)),
                ('student_name', models.CharField(max_length=255)),
                ('dept', models.CharField(max_length=255)),
                ('year', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
