# Generated by Django 5.0.3 on 2024-03-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0009_student_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='student_id',
        ),
    ]
