# Generated by Django 5.0.4 on 2024-04-15 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0012_student_register_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_purchase',
            name='issuedate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='student_purchase',
            name='submit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
