# Generated by Django 5.0.4 on 2024-04-18 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0015_alter_student_purchase_issuedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_purchase',
            name='issuedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student_purchase',
            name='submit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
